public class Calc extends javax.swing.JFrame {

    String operators = null; /** empty box labeled "operators" that will be filled with a specific mathematical operator later**/
    double number1 = 0,  number2 = 0;
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttEnt = new javax.swing.JTextField();
        buadd = new javax.swing.JButton();
        buans = new javax.swing.JButton();
        budel = new javax.swing.JButton();
        buC = new javax.swing.JButton();
        bu1 = new javax.swing.JButton();
        bu7 = new javax.swing.JButton();
        bu4 = new javax.swing.JButton();
        bu2 = new javax.swing.JButton();
        bu8 = new javax.swing.JButton();
        bu5 = new javax.swing.JButton();
        bu3 = new javax.swing.JButton();
        bu9 = new javax.swing.JButton();
        bu6 = new javax.swing.JButton();
        bu0 = new javax.swing.JButton();
        butDot = new javax.swing.JButton();
        budiv = new javax.swing.JButton();
        bumin = new javax.swing.JButton();
        bumul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULATOR");

        buttEnt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        buttEnt.setText("Enter the values and operation");
        buttEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEntActionPerformed(evt);
            }
        });

        buadd.setText("+");
        buadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buaddActionPerformed(evt);
            }
        });

        buans.setText("ANS");
        buans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buansActionPerformed(evt);
            }
        });

        budel.setText("DEL");
        budel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budelActionPerformed(evt);
            }
        });

        buC.setText("C");
        buC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCActionPerformed(evt);
            }
        });

        bu1.setText("1");
        bu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu1ActionPerformed(evt);
            }
        });

        bu7.setText("7");
        bu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu7ActionPerformed(evt);
            }
        });

        bu4.setText("4");
        bu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu4ActionPerformed(evt);
            }
        });

        bu2.setText("2");
        bu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu2ActionPerformed(evt);
            }
        });

        bu8.setText("8");
        bu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu8ActionPerformed(evt);
            }
        });

        bu5.setText("5");
        bu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu5ActionPerformed(evt);
            }
        });

        bu3.setText("3");
        bu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu3ActionPerformed(evt);
            }
        });

        bu9.setText("9");
        bu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu9ActionPerformed(evt);
            }
        });

        bu6.setText("6");
        bu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu6ActionPerformed(evt);
            }
        });

        bu0.setText("0");
        bu0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu0ActionPerformed(evt);
            }
        });

        butDot.setText(".");
        butDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDotActionPerformed(evt);
            }
        });

        budiv.setText("/");
        budiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budivActionPerformed(evt);
            }
        });

        bumin.setText("-");
        bumin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buminActionPerformed(evt);
            }
        });

        bumul.setText("*");
        bumul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bumulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttEnt)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(budel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bumin, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(bumul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(budiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bu7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(bu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bu5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bu8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bu9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buadd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buans, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(buttEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buadd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(budel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buC, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bu9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bu6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bu3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bu8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bu7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bu5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bu2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bu1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(bu4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bu0, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(butDot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bumin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bumul, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(budiv, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEntActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_buttEntActionPerformed

    private void buaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buaddActionPerformed
        number1 = Double.parseDouble(buttEnt.getText());
        buttEnt.setText("");
        operators = "+";
    }//GEN-LAST:event_buaddActionPerformed

    private void budivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budivActionPerformed
        number1 = Double.parseDouble(buttEnt.getText());
        buttEnt.setText("");
        operators = "/";
    }//GEN-LAST:event_budivActionPerformed

    private void bu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu3ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"3");
    }//GEN-LAST:event_bu3ActionPerformed

    private void bu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu1ActionPerformed
        // TODO add your handling code here:
        buttEnt.setText(buttEnt.getText()+"1");
    }//GEN-LAST:event_bu1ActionPerformed

    private void bu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu2ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"2");
    }//GEN-LAST:event_bu2ActionPerformed

    private void bu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu4ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"4");
    }//GEN-LAST:event_bu4ActionPerformed

    private void bu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu5ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"5");
    }//GEN-LAST:event_bu5ActionPerformed

    private void bu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu6ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"6");
    }//GEN-LAST:event_bu6ActionPerformed

    private void bu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu7ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"7");
    }//GEN-LAST:event_bu7ActionPerformed

    private void bu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu8ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"8");
    }//GEN-LAST:event_bu8ActionPerformed

    private void bu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu9ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"9");
    }//GEN-LAST:event_bu9ActionPerformed

    private void bu0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu0ActionPerformed
        // TODO add your handling code here:
         buttEnt.setText(buttEnt.getText()+"0");
    }//GEN-LAST:event_bu0ActionPerformed

    private void buminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buminActionPerformed
        number1 = Double.parseDouble(buttEnt.getText());
        buttEnt.setText("");
        operators = "-";
    }//GEN-LAST:event_buminActionPerformed

    private void bumulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bumulActionPerformed
       number1 = Double.parseDouble(buttEnt.getText());
        buttEnt.setText("");
        operators = "*";
    }//GEN-LAST:event_bumulActionPerformed

    private void butDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butDotActionPerformed

    private void buansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buansActionPerformed
      number2 = Double.parseDouble(buttEnt.getText()) ;
         
         double result = 0;
         
         if(operators=="+")
             result=number1+number2;
         else if(operators=="-")
             result=number1-number2;
         else if(operators=="*")
             result=number1*number2;
         else if(operators=="/")
             result=number1/number2;
         
         buttEnt.setText(result+"");
         
         operators=null;  
    }//GEN-LAST:event_buansActionPerformed

    private void budelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budelActionPerformed
       buttEnt.setText("");
    }//GEN-LAST:event_budelActionPerformed

    private void buCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCActionPerformed
       String s = buttEnt.getText();
        
        buttEnt.setText(s.substring(0,s.length()-1));
    }//GEN-LAST:event_buCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu0;
    private javax.swing.JButton bu1;
    private javax.swing.JButton bu2;
    private javax.swing.JButton bu3;
    private javax.swing.JButton bu4;
    private javax.swing.JButton bu5;
    private javax.swing.JButton bu6;
    private javax.swing.JButton bu7;
    private javax.swing.JButton bu8;
    private javax.swing.JButton bu9;
    private javax.swing.JButton buC;
    private javax.swing.JButton buadd;
    private javax.swing.JButton buans;
    private javax.swing.JButton budel;
    private javax.swing.JButton budiv;
    private javax.swing.JButton bumin;
    private javax.swing.JButton bumul;
    private javax.swing.JButton butDot;
    private javax.swing.JTextField buttEnt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
